/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardCategoriasRouteImport } from './routes/dashboard.categorias'
import { Route as DashboardConfiguracoesRouteImport } from './routes/dashboard.configuracoes'
import { Route as DashboardPedidosRouteImport } from './routes/dashboard.pedidos'
import { Route as DashboardProdutosRouteImport } from './routes/dashboard.produtos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriasRoute = DashboardCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracoesRoute = DashboardConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPedidosRoute = DashboardPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProdutosRoute = DashboardProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrinho': typeof CarrinhoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/categorias': typeof DashboardCategoriasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/pedidos': typeof DashboardPedidosRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrinho': typeof CarrinhoRoute
  '/dashboard/categorias': typeof DashboardCategoriasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/pedidos': typeof DashboardPedidosRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrinho': typeof CarrinhoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/categorias': typeof DashboardCategoriasRoute
  '/dashboard/configuracoes': typeof DashboardConfiguracoesRoute
  '/dashboard/pedidos': typeof DashboardPedidosRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carrinho'
    | '/dashboard'
    | '/dashboard/categorias'
    | '/dashboard/configuracoes'
    | '/dashboard/pedidos'
    | '/dashboard/produtos'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/carrinho'
    | '/dashboard/categorias'
    | '/dashboard/configuracoes'
    | '/dashboard/pedidos'
    | '/dashboard/produtos'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/carrinho'
    | '/dashboard'
    | '/dashboard/categorias'
    | '/dashboard/configuracoes'
    | '/dashboard/pedidos'
    | '/dashboard/produtos'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CarrinhoRoute: typeof CarrinhoRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categorias': {
      id: '/dashboard/categorias'
      path: '/categorias'
      fullPath: '/dashboard/categorias'
      preLoaderRoute: typeof DashboardCategoriasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuracoes': {
      id: '/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof DashboardConfiguracoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pedidos': {
      id: '/dashboard/pedidos'
      path: '/pedidos'
      fullPath: '/dashboard/pedidos'
      preLoaderRoute: typeof DashboardPedidosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/produtos': {
      id: '/dashboard/produtos'
      path: '/produtos'
      fullPath: '/dashboard/produtos'
      preLoaderRoute: typeof DashboardProdutosRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCategoriasRoute: typeof DashboardCategoriasRoute
  DashboardConfiguracoesRoute: typeof DashboardConfiguracoesRoute
  DashboardPedidosRoute: typeof DashboardPedidosRoute
  DashboardProdutosRoute: typeof DashboardProdutosRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCategoriasRoute: DashboardCategoriasRoute,
  DashboardConfiguracoesRoute: DashboardConfiguracoesRoute,
  DashboardPedidosRoute: DashboardPedidosRoute,
  DashboardProdutosRoute: DashboardProdutosRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CarrinhoRoute: CarrinhoRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
